---
- name: Install Core Packages
  action: apt pkg={{ item }}
  with_items:
    - git
    - ruby
    - curl
    - patch
    - bzip2
    - openssl
    - ca-certificates
    - build-essential
    - cmake
    - autoconf
    - automake
    - python-mysqldb # Needed by ansible mysql_* modules
    - python-software-properties # Needed by ansible apt_repository¶