---
- name: Install MySQL database server
  action: apt pkg=mysql-server
  register: mysql_server

- name: Set MySQL root password
  action: shell mysqladmin -u root password {{mysql_root_password}}
  when: mysql_server.changed

- name: Install MySQL utilities and related package
  action: apt pkg={{ item }}
  with_items:
    - mysql-client
    - python-mysqldb # This is needed by ansible mysql_* modules
