---
- name: Install Python 2.7 Packages
  action: apt pkg={{ item }}
  with_items:
    - python
    - python-setuptools
    - python-dev

- name: Add Python 3.3 backports apt sources
  action: apt_repository repo=ppa:fkrull/deadsnakes

- name: Update apt cache after adding Python 3.3 backport sources
  action: apt update_cache=yes

- name: Install Python 3.3 Packages
  # not sure why the force=yes is necessary...
  action: apt pkg={{ item }} force=yes
  with_items:
    - python3.3
    - python3.3-dev

- name: Install virtualenv
  action: easy_install name=virtualenv

- name: Install virtualenvwrapper
  action: easy_install name=virtualenvwrapper
