---
- name: Assign git host as a SSH known host
  known_hosts: host={{ git_hostname }} state=present
               file=/home/wiki/.ssh/known_hosts
               user=wiki group=wiki

- name: Test to see if the wiki repository has been cloned
  action: shell test -d /home/wiki/wiki
  register: repository_cloned
  ignore_errors: True

- name: Git clone wiki repository
  action: shell sudo -u wiki -i git clone
                git@{{ git_hostname }}:wiki.git /home/wiki/wiki
  when: repository_cloned|failed

- name: Create wiki repository update.sh
  action: copy src=update.sh
               dest=/home/wiki/update.sh
               mode=0755 owner=wiki group=wiki

- name: Test to see if the wiki site has been built
  action: shell test -d /home/wiki/wiki/_site
  register: wiki_site_built
  ignore_errors: True

- name: Build wiki site
  action: shell sudo -u wiki -i /home/wiki/update.sh
  when: wiki_site_built|failed

- name: Create wiki repository post-receive hook
  action: copy src=post-receive.sh
               dest=/home/git/repositories/wiki.git/hooks/post-receive
               mode=0750 owner=git group=git
