---
- name: Install RVM build dependencies for Ruby 1.9.3
  action: apt pkg={{ item }}
  with_items:
    - gawk
    - libyaml-dev
    - sqlite3
    - libgdbm-dev
    - libncurses5-dev
    - libtool
    - bison
    - libffi-dev

- name: Test to see if RVM is installed
  action: shell test -d /home/wiki/.rvm
  register: rvm_installed
  ignore_errors: True

- name: Install RVM
  action: shell sudo -u wiki -i bash -l -c
                'curl https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer | bash -s stable'
  when: rvm_installed|failed

- name: Install Ruby 1.9.3 for wiki
  action: shell sudo -u wiki -i bash -l -c 'rvm install 1.9.3'
  when: rvm_installed|failed

- name: Install Gollum gem (or its dependent gems) dependencies
  action: apt pkg={{ item }}
  with_items:
    - libxml2-dev
    - libxslt1-dev
