---
- name: Create the wiki group
  action: group name=wiki

- name: Create the wiki user
  action: user name=wiki group=wiki shell=/bin/bash
               home=/home/wiki comment='Wiki generator'

- name: Create wiki's SSH directory
  action: file path=/home/wiki/.ssh state=directory
               mode=0700 owner=wiki group=wiki

- name: Create wiki's SSH private key
  action: template src=wiki-id_rsa
               dest=/home/wiki/.ssh/id_rsa
               mode=0600 owner=wiki group=wiki

- name: Create wiki's SSH public key
  action: copy src=wiki-id_rsa.pub
              dest=/home/wiki/.ssh/id_rsa.pub
              mode=0644 owner=wiki group=wiki

- name: Allow wiki user to sudo to git
  action: >
    lineinfile dest=/etc/sudoers
               regexp=/home/wiki/update\.sh
               insertafter=EOF
               line='git ALL = (wiki) NOPASSWD: /home/wiki/update.sh'
