- hosts: all
  sudo: True
  tasks:
    - name: Creates destination directory
      file: state=directory owner=root mode=0700 dest=/root/.ssh
    - name: Pushes user's rsa key to root's vagrant box
      action: copy src=~/.ssh/id_rsa.pub dest=/root/.ssh/authorized_keys owner=root mode=0600
