---
- name: Install dependencies to build mod-browserid
  action: apt pkg=libcurl4-openssl-dev,apache2-prefork-dev

- name: See if mod-browserid is installed
  action: shell test -f /usr/lib/apache2/modules/mod_auth_browserid.so
  register: mod_browserid_installed
  ignore_errors: True

- name: Install mod-browserid
  action: script install-mod-browserid
  when: mod_browserid_installed|failed

- name: Create Apache module load configuration for mod-browserid
  action: copy src=auth_browserid.load
               dest=/etc/apache2/mods-available/auth_browserid.load
               mode=0644

- name: Enable Apache mod-browserid module
  action: file src=/etc/apache2/mods-available/auth_browserid.load
               path=/etc/apache2/mods-enabled/auth_browserid.load
               state=link
  notify: Restart Apache
