---
- name: See if yajl2 is installed
  action: shell test -f /usr/local/lib/libyajl.so
  register: yajl2_installed
  ignore_errors: True

- name: Install yajl2
  action: script install-yajl2
  when: yajl2_installed|failed
