---
- hosts: all
  user: root
  vars_files:
    - secrets.yml
  tasks:
    - include: wiki/tasks/wiki-user.yml
    - include: wiki/tasks/rvm.yml
    - include: wiki/tasks/repository.yml
  handlers:
    - name: Restart Apache
      action: service name=apache2 state=restarted
