---
- hosts: all
  user: root
  vars_files:
    - ../../secrets.yml
  tasks:
    - include: yajl2.yml
    - include: mod-browserid.yml
    - include: persona-config.yml
  handlers:
    - name: Restart Apache
      action: service name=apache2 state=restarted
