---
- name: Install dependencies to build mod-browserid
  action: apt pkg=libcurl4-openssl-dev,apache2-prefork-dev

- name: See if mod-browserid is installed
  action: command /usr/bin/test -f /usr/lib/apache2/modules/mod_auth_browserid.so
  register: result
  ignore_errors: True

- name: Install mod-browserid
  action: script install-mod-browserid
  when: result|failed

- name: Create Apache module load configuration for mod-browserid
  action: copy src=auth_browserid.load dest=/etc/apache2/mods-available/auth_browserid.load mode=0644 owner=root

- name: Enable Apache mod-browserid module
  action: file src=/etc/apache2/mods-available/auth_browserid.load path=/etc/apache2/mods-enabled/auth_browserid.load state=link owner=root
  notify: Restart Apache
