---
- name: Install Core Packages (git, ruby, development, etc.)
  action: apt pkg={{ item }}
  with_items:
    - git
    - ruby
    - curl
    - patch
    - bzip2
    - openssl
    - ca-certificates
    - build-essential
    - cmake
    - autoconf
    - automake
