---
- hosts: all
  user: root
  vars_files:
    - ../../secrets.yml
  tasks:
    - include: timezone.yml
    - include: firewall.yml
    - include: apt.yml
    - include: core-packages.yml
    - include: postfix.yml
    - include: apache.yml
    - include: mysql.yml
    - include: php.yml
  handlers:
    - name: Restart Apache
      action: service name=apache2 state=restarted
