---
- name: Download the New Relic apt configuration
  action: get_url url=https://download.newrelic.com/debian/newrelic.list
                  dest=/etc/apt/sources.list.d/newrelic.list

- name: Detect if we have the New Relic GPG key
  action: shell apt-key list | grep 548C16BF
  register: new_relic_key
  ignore_errors: true

- name: Add the New Relic GPG key
  action: shell apt-key adv --keyserver hkp://subkeys.pgp.net
                            --recv-keys 548C16BF
  when: new_relic_key|failed

- name: Add the New Relic monitoring package
  action: apt update_cache=yes pkg=newrelic-sysmond
  register: newrelic_package

- name: Set New Relic license key
  action: shell nrsysmond-config --set license_key={{ newrelic_license_key }}
  when: newrelic_package.changed

- name: Start New Relic monitor
  action: service name=newrelic-sysmond state=restarted
