---
- hosts: all
  user: root
  vars:
    repository_archive_path: ../../seeds/sc-git-repositories.tar.bz2
  vars_files:
    - ../../secrets.yml

  tasks:

    - name: Create a git group
      action: group name=git system=yes

    - name: Create a git user
      action: user name=git system=yes createhome=yes group=git
              shell=/bin/bash comment='git version control'

    - include: gitolite.yml

    - include: gitweb.yml

  handlers:

    - name: Restart Apache
      action: service name=apache2 state=restarted
